export const GameEvents = {
	PLAY_REQUESTED: 'PLAY_REQUESTED',

	BET_CHANGE_REQUEST: 'BET_CHANGE_REQUEST',
	COLOR_CHANGE_REQUEST: 'COLOR_CHANGE_REQUEST',

	BET_UPDATED: 'BET_UPDATED',
	COLOR_UPDATED: 'COLOR_UPDATED',

	BALANCE_CHANGED: 'BALANCE_CHANGED',
	STATE_CHANGED: 'STATE_CHANGED',

	ROUND_STARTED: 'ROUND_STARTED',
	WHEEL_SPIN_COMPLETED: 'WHEEL_SPIN_COMPLETED',

	RESULT_READY: 'RESULT_READY',
	RESULT_HIDDEN: 'RESULT_HIDDEN',
};
